import 'package:rosewell_life_science/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterPhoneNumber: "Please enter phone number.",
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number.",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password.",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.fileIsSavedToDownloadFolder: "File is saved to download folder.",
  AppStrings.next: "Next",
  AppStrings.areYouSureYouWantToExitTheApp: "Are you sure you want to exit the app?",
  AppStrings.no: "No",
  AppStrings.yesExit: "Yes, exit",
  AppStrings.hello: "Hello ",
  AppStrings.presentationForDoctors: "Presentation for Doctors",
  AppStrings.presentation: "Presentation",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'Log Out',
  AppStrings.noDataFound: "No data found",
  AppStrings.medicineDetails: "Medicine Details",
  AppStrings.addMedicineDetails: "Add Medicine Details",
  AppStrings.editMedicineDetails: "Edit Medicine Details",
  AppStrings.addMedicine: "Add Medicine",
  AppStrings.editMedicine: "Edit Medicine",
  AppStrings.medicineName: "Medicine Name",
  AppStrings.enterMedicineName: "Enter medicine name",
  AppStrings.pleaseEnterMedicineName: "Please enter medicine name.",
  AppStrings.imagesOfMedicine: "Images of Medicine",
  AppStrings.chooseImagesFromYourDevice: "Choose images from your device.",
  AppStrings.addMoreImages: "Add more images",
  AppStrings.add: "Add",
  AppStrings.pleaseChooseImages: "Please choose images.",
  AppStrings.edit: "Edit",
  AppStrings.listOfMedicine: "List of Medicine",
  AppStrings.reset: "Reset",
  AppStrings.pleaseSelectMedicine: "Please select medicine.",
  AppStrings.selectMedicine: "Select Medicine",
  AppStrings.searchMedicine: "Search Medicine",
  AppStrings.addDoctor: "Add Doctor",
  AppStrings.editDoctor: "Edit Doctor",
  AppStrings.select: "Select",
  AppStrings.doctorName: "Doctor Name",
  AppStrings.enterDoctorName: "Enter doctor name",
  AppStrings.pleaseEnterDoctorName: "Please enter doctor name.",
  AppStrings.noMedicineHasBeenSelected: "No medicine has been selected.",
  AppStrings.view: "View",
};
