import 'package:rosewell_life_science/Constants/app_strings.dart';

Map<String, String> enIN = <String, String>{
  AppStrings.login: "Login",
  AppStrings.phoneNumber: "Phone Number",
  AppStrings.enterPhoneNumber: "Enter phone number",
  AppStrings.pleaseEnterPhoneNumber: "Please enter phone number.",
  AppStrings.pleaseEnterValidPhoneNumber: "Please enter valid phone number.",
  AppStrings.password: "Password",
  AppStrings.enterPassword: "Enter password",
  AppStrings.pleaseEnterPassword: "Please enter password.",
  AppStrings.temporaryServiceIsNotAvailable: "Temporary service is not available.",
  AppStrings.fileIsSavedToDownloadFolder: "File is saved to download folder.",
  AppStrings.next: "Next",
  AppStrings.hello: "Hello 👋,",
  AppStrings.createOrder: "Create Order",
  AppStrings.settings: "Settings",
  AppStrings.changeLanguage: "Change Language",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.addStock: "Add Stock",
  AppStrings.availableStock: "Available Stock",
  AppStrings.pendingOrders: "Pending Orders",
  AppStrings.challan: "Challan",
  AppStrings.category: "Category",
  AppStrings.selectCategory: "Select Category",
  AppStrings.noDataFound: "No data found",
  AppStrings.handle: "Handle",
  AppStrings.mainDoor: "Main Door",
  AppStrings.dabbi: "Dabbi",
  AppStrings.pleaseSelectCategory: "Please select category.",
  AppStrings.add: "Add",
  AppStrings.product: "Product",
  AppStrings.selectProduct: "Select Product",
  AppStrings.pleaseSelectProduct: "Please select product.",
  AppStrings.enterProductName: "Enter Product Name",
  AppStrings.size: "Size",
  AppStrings.selectSize: "Select Size",
  AppStrings.select: "Select",
  AppStrings.searchSize: "Search size",
  AppStrings.searchProduct: "Search product",
  AppStrings.three: '3',
  AppStrings.four: '4',
  AppStrings.six: '6',
  AppStrings.eight: '8',
  AppStrings.ten: '10',
  AppStrings.twelve: '12',
  AppStrings.enterProductSize: 'Enter Product Size',
  AppStrings.size3QuantityWeight: 'Size 3 Quantity & Weight',
  AppStrings.size4QuantityWeight: 'Size 4 Quantity & Weight',
  AppStrings.size6QuantityWeight: 'Size 6 Quantity & Weight',
  AppStrings.size8QuantityWeight: 'Size 8 Quantity & Weight',
  AppStrings.size10QuantityWeight: 'Size 10 Quantity & Weight',
  AppStrings.size12QuantityWeight: 'Size 12 Quantity & Weight',
  AppStrings.enterQuantity: 'Enter Quantity (Piece)',
  AppStrings.enterWeight: 'Enter Weight (Kg)',
  AppStrings.enterWeightOfSinglePiece: 'Enter Weight Of Single Piece',
  AppStrings.pleaseEnterProductSize: 'Please enter product size.',
  AppStrings.pleaseSelectProductSize: 'Please select product size.',
  AppStrings.pleaseEnterQuantity: 'Please enter quantity.',
  AppStrings.pleaseEnterWeight: 'Please enter weight.',
  AppStrings.reset: 'Reset',
  AppStrings.gram: 'Gram (g)',
  AppStrings.kilogram: 'Kilogram (kg)',
  AppStrings.pleaseSelectUnitOfWeight: 'Please select unit of weight.',
  AppStrings.selectUnitOfWeight: 'Select Unit Of Weight',
  AppStrings.firstEnterWeightOfSinglePieceAndUnitOfWeight: 'First enter weight of single piece and unit of weight.',
  AppStrings.quantityMustBeAFractionValue: 'Quantity must be a fraction value.',
  AppStrings.logOut: 'Log Out',
  AppStrings.loginSuccessfully: 'Login Successfully',
  AppStrings.invalidPhoneOrPassword: 'Invalid Phone OR Password',
  AppStrings.weightOfPiece: 'Weight of Piece: ',
  AppStrings.availableStockQuantityWeight: 'Available Stock (Quantity/Weight[kg]): ',
  AppStrings.pieces: ' pieces',
  AppStrings.orderOfSize3: 'Order Of Size 3',
  AppStrings.orderOfSize4: 'Order Of Size 4',
  AppStrings.orderOfSize6: 'Order Of Size 6',
  AppStrings.orderOfSize8: 'Order Of Size 8',
  AppStrings.orderOfSize10: 'Order Of Size 10',
  AppStrings.orderOfSize12: 'Order Of Size 12',
  AppStrings.orderOfSizeCustom: 'Order Of Size Custom',
  AppStrings.pleaseSelectAnySizeForTheOrder: 'Please select any size for the order.',
  AppStrings.ordersHistory: 'Orders History',
  AppStrings.addNewProduct: 'Add New Product',
  AppStrings.pleaseEnterProductName: 'Please enter product name.',
  AppStrings.totalQuantity: 'Total quantity: ',
  AppStrings.totalWeight: 'Total weight: ',
  AppStrings.quantity: 'Quantity: ',
  AppStrings.weight: 'Weight: ',
  AppStrings.thisSizeOfProductNotRegistered: 'This size of product is not registered. First, add the size through \'Add Stock\'.',
  AppStrings.done: 'Done',
  AppStrings.cancel: 'Cancel',
  AppStrings.orderDate: 'Order Date: ',
  AppStrings.orderTime: 'Order Time: ',
  AppStrings.quantityAndWeight: 'Quantity & Weight',
  AppStrings.partyName: 'Party Name',
  AppStrings.enterPartyName: 'Enter party name',
  AppStrings.pleaseEnterPartyName: 'Please enter party name.',
  AppStrings.productName: 'Product Name: ',
  AppStrings.stockNotAvailable: 'Stock Not Available',
};
