import 'package:rosewell_life_science/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો.",
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો.",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો.",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.fileIsSavedToDownloadFolder: "ફાઇલ ડાઉનલોડ ફોલ્ડરમાં સાચવવામાં આવે છે.",
  AppStrings.next: "આગળ",
  AppStrings.areYouSureYouWantToExitTheApp: "શું તમે ખરેખર એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?",
  AppStrings.no: "ના",
  AppStrings.yesExit: "હા, બહાર નીકળો",
  AppStrings.hello: "નમસ્તે ",
  AppStrings.presentationForDoctors: "ડોકટરો માટે રજૂઆત",
  AppStrings.presentation: "રજૂઆત",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'લૉગ આઉટ',
  AppStrings.noDataFound: "કોઈ ડેટા મળ્યો નથી",
  AppStrings.medicineDetails: "દવાની વિગતો",
  AppStrings.addMedicineDetails: "દવાની વિગતો ઉમેરો",
  AppStrings.editMedicineDetails: "દવાની વિગતો સંપાદિત કરો",
  AppStrings.addMedicine: "દવા ઉમેરો",
  AppStrings.editMedicine: "દવા સંપાદિત કરો",
};
