import 'package:rosewell_life_science/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો.",
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો.",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો.",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.fileIsSavedToDownloadFolder: "ફાઇલ ડાઉનલોડ ફોલ્ડરમાં સાચવવામાં આવે છે.",
  AppStrings.next: "આગળ",
  AppStrings.hello: "નમસ્તે 🙏,",
  AppStrings.createOrder: "ઓર્ડર ઉમેરો",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.addStock: "સ્ટોક ઉમેરો",
  AppStrings.availableStock: "ઉપલબ્ધ સ્ટોક",
  AppStrings.pendingOrders: "બાકી ઓર્ડર",
  AppStrings.challan: "ચલણ",
  AppStrings.category: "શ્રેણી",
  AppStrings.selectCategory: "શ્રેણી પસંદ કરો",
  AppStrings.noDataFound: "કોઈ ડેટા મળ્યો નથી",
  AppStrings.handle: "હેન્ડલ",
  AppStrings.mainDoor: "મેઈન ડોર",
  AppStrings.dabbi: "ડબ્બી",
  AppStrings.pleaseSelectCategory: "કૃપા કરીને શ્રેણી પસંદ કરો.",
  AppStrings.add: "ઉમેરો",
  AppStrings.product: "પ્રોડક્ટ",
  AppStrings.selectProduct: "પ્રોડક્ટ પસંદ કરો",
  AppStrings.pleaseSelectProduct: "કૃપા કરીને પ્રોડક્ટ પસંદ કરો.",
  AppStrings.enterProductName: "પ્રોડક્ટ નામ દાખલ કરો",
  AppStrings.size: "સાઈઝ",
  AppStrings.selectSize: "સાઈઝ પસંદ કરો",
  AppStrings.select: "પસંદ કરો",
  AppStrings.searchSize: "સાઈઝ શોધો",
  AppStrings.searchProduct: "પ્રોડક્ટ શોધો",
  AppStrings.three: '૩',
  AppStrings.four: '૪',
  AppStrings.six: '૬',
  AppStrings.eight: '૮',
  AppStrings.ten: '૧૦',
  AppStrings.twelve: '૧૨',
  AppStrings.enterProductSize: 'પ્રોડક્ટની સાઈઝ દાખલ કરો',
  AppStrings.size3QuantityWeight: 'સાઈઝ ૩ જથ્થો અને વજન',
  AppStrings.size4QuantityWeight: 'સાઈઝ ૪ જથ્થો અને વજન',
  AppStrings.size6QuantityWeight: 'સાઈઝ ૬ જથ્થો અને વજન',
  AppStrings.size8QuantityWeight: 'સાઈઝ ૮ જથ્થો અને વજન',
  AppStrings.size10QuantityWeight: 'સાઈઝ ૧૦ જથ્થો અને વજન',
  AppStrings.size12QuantityWeight: 'સાઈઝ ૧૨ જથ્થો અને વજન',
  AppStrings.enterQuantity: 'જથ્થો દાખલ કરો (નંગ)',
  AppStrings.enterWeight: 'વજન દાખલ કરો (કિગ્રા)',
  AppStrings.enterWeightOfSinglePiece: 'એક પીસનું વજન દાખલ કરો',
  AppStrings.pleaseEnterProductSize: 'કૃપા કરીને પ્રોડક્ટની સાઈઝ દાખલ કરો.',
  AppStrings.pleaseSelectProductSize: 'કૃપા કરીને પ્રોડક્ટની સાઈઝ પસંદ કરો.',
  AppStrings.pleaseEnterQuantity: 'કૃપા કરીને જથ્થો દાખલ કરો.',
  AppStrings.pleaseEnterWeight: 'કૃપા કરીને વજન દાખલ કરો.',
  AppStrings.reset: 'રીસેટ કરો',
  AppStrings.gram: 'ગ્રામ',
  AppStrings.kilogram: 'કિલોગ્રામ (કિલો)',
  AppStrings.pleaseSelectUnitOfWeight: 'કૃપા કરીને વજનનું એકમ પસંદ કરો.',
  AppStrings.selectUnitOfWeight: 'વજનનું એકમ પસંદ કરો',
  AppStrings.firstEnterWeightOfSinglePieceAndUnitOfWeight: 'પ્રથમ એક પીસનું વજન અને વજનનું એકમ દાખલ કરો.',
  AppStrings.quantityMustBeAFractionValue: 'જથ્થો અપૂર્ણાંક મૂલ્ય હોવો જોઈએ.',
  AppStrings.logOut: 'લૉગ આઉટ',
  AppStrings.loginSuccessfully: 'સફળતાપૂર્વક લૉગિન',
  AppStrings.invalidPhoneOrPassword: 'અમાન્ય ફોન અથવા પાસવર્ડ',
  AppStrings.weightOfPiece: 'પીસનું વજન: ',
  AppStrings.availableStockQuantityWeight: 'ઉપલબ્ધ સ્ટોક (જથ્થા/વજન[કિલો]): ',
  AppStrings.pieces: ' નંગ',
  AppStrings.orderOfSize3: 'સાઈઝ ૩ નો ઓર્ડર',
  AppStrings.orderOfSize4: 'સાઈઝ ૪ નો ઓર્ડર',
  AppStrings.orderOfSize6: 'સાઈઝ ૬ નો ઓર્ડર',
  AppStrings.orderOfSize8: 'સાઈઝ ૮ નો ઓર્ડર',
  AppStrings.orderOfSize10: 'સાઈઝ ૧૦ નો ઓર્ડર',
  AppStrings.orderOfSize12: 'સાઈઝ ૧૨ નો ઓર્ડર',
  AppStrings.orderOfSizeCustom: 'સાઈઝ કસ્ટમ નો ઓર્ડર',
  AppStrings.pleaseSelectAnySizeForTheOrder: 'કૃપા કરીને ઓર્ડર માટે કોઈપણ કદ પસંદ કરો.',
  AppStrings.ordersHistory: 'ઓર્ડર્સની યાદી',
  AppStrings.addNewProduct: 'નવું ઉત્પાદન ઉમેરો',
  AppStrings.pleaseEnterProductName: 'કૃપા કરીને પ્રોડક્ટનું નામ દાખલ કરો.',
  AppStrings.totalQuantity: 'કુલ જથ્થો: ',
  AppStrings.totalWeight: 'કૂલ વજન: ',
  AppStrings.quantity: 'જથ્થો: ',
  AppStrings.weight: 'વજન: ',
  AppStrings.thisSizeOfProductNotRegistered: 'ઉત્પાદનની આ સાઈઝ નોંધાયેલ નથી. પ્રથમ, \'એડ સ્ટોક\' દ્વારા સાઈઝ ઉમેરો.',
  AppStrings.done: 'પૂર્ણ',
  AppStrings.cancel: 'રદ કરો',
  AppStrings.orderDate: 'ઓર્ડર તારીખ: ',
  AppStrings.orderTime: 'ઓર્ડર સમય: ',
  AppStrings.quantityAndWeight: 'જથ્થો અને વજન',
  AppStrings.partyName: 'પાર્ટીનું નામ',
  AppStrings.enterPartyName: 'પાર્ટીનું નામ દાખલ કરો',
  AppStrings.pleaseEnterPartyName: 'કૃપા કરીને પાર્ટીનું નામ દાખલ કરો.',
  AppStrings.productName: 'ઉત્પાદન નામ: ',
  AppStrings.stockNotAvailable: 'સ્ટોક ઉપલબ્ધ નથી',
};
