import 'package:rosewell_life_science/Constants/app_strings.dart';

Map<String, String> guIN = <String, String>{
  AppStrings.login: "પ્રવેશ કરો",
  AppStrings.phoneNumber: "ફોન નંબર",
  AppStrings.enterPhoneNumber: "ફોન નંબર દાખલ કરો",
  AppStrings.pleaseEnterPhoneNumber: "કૃપા કરીને ફોન નંબર દાખલ કરો.",
  AppStrings.pleaseEnterValidPhoneNumber: "કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો.",
  AppStrings.cityName: "શહેરનું નામ",
  AppStrings.enterCityName: "શહેરનું નામ દાખલ કરો",
  AppStrings.pleaseEnterCityName: "કૃપા કરીને શહેરનું નામ દાખલ કરો.",
  AppStrings.password: "પાસવર્ડ",
  AppStrings.enterPassword: "પાસવર્ડ દાખલ કરો",
  AppStrings.pleaseEnterPassword: "કૃપા કરીને પાસવર્ડ દાખલ કરો.",
  AppStrings.temporaryServiceIsNotAvailable: "હાલમાં સેવા ઉપલબ્ધ નથી.",
  AppStrings.fileIsSavedToDownloadFolder: "ફાઇલ ડાઉનલોડ ફોલ્ડરમાં સાચવવામાં આવે છે.",
  AppStrings.next: "આગળ",
  AppStrings.areYouSureYouWantToExitTheApp: "શું તમે ખરેખર એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?",
  AppStrings.no: "ના",
  AppStrings.yesExit: "હા, બહાર નીકળો",
  AppStrings.hello: "નમસ્તે ",
  AppStrings.presentationForDoctors: "ડોકટરો માટે રજૂઆત",
  AppStrings.presentation: "રજૂઆત",
  AppStrings.settings: "સેટિંગ્સ",
  AppStrings.changeLanguage: "ભાષા બદલો",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'લૉગ આઉટ',
  AppStrings.noDataFound: "કોઈ ડેટા મળ્યો નથી",
  AppStrings.medicineDetails: "દવાની વિગતો",
  AppStrings.addMedicineDetails: "દવાની વિગતો ઉમેરો",
  AppStrings.editMedicineDetails: "દવાની વિગતો સંપાદિત કરો",
  AppStrings.addMedicine: "દવા ઉમેરો",
  AppStrings.editMedicine: "દવા સંપાદિત કરો",
  AppStrings.medicineName: "દવાનું નામ",
  AppStrings.enterMedicineName: "દવાનું નામ દાખલ કરો",
  AppStrings.imagesOfMedicine: "દવાની છબીઓ",
  AppStrings.chooseImagesFromYourDevice: "તમારા ઉપકરણમાંથી છબીઓ પસંદ કરો.",
  AppStrings.addMoreImages: "વધુ છબીઓ ઉમેરો",
  AppStrings.add: "ઉમેરો",
  AppStrings.pleaseChooseImages: "કૃપા કરીને છબીઓ પસંદ કરો.",
  AppStrings.edit: "સંપાદિત કરો",
  AppStrings.listOfMedicine: "દવાની સૂચિ",
  AppStrings.pleaseSelectMedicine: "કૃપા કરીને દવા પસંદ કરો.",
  AppStrings.selectMedicine: "દવા પસંદ કરો",
  AppStrings.searchMedicine: "દવા શોધો",
  AppStrings.addDoctor: "ડૉક્ટર ઉમેરો",
  AppStrings.editDoctor: "ડૉક્ટર સંપાદિત કરો",
  AppStrings.select: "પસંદ કરો",
  AppStrings.doctorName: "ડોક્ટરનું નામ",
  AppStrings.enterDoctorName: "ડૉક્ટરનું નામ દાખલ કરો",
  AppStrings.pleaseEnterDoctorName: "કૃપા કરીને ડૉક્ટરનું નામ દાખલ કરો.",
  AppStrings.noMedicineHasBeenSelected: "કોઈ દવા પસંદ કરવામાં આવી નથી.",
  AppStrings.view: "જુઓ",
  AppStrings.listOfDoctors: "ડોકટરોની યાદી",
  AppStrings.pleaseSelectDoctor: "કૃપા કરીને ડૉક્ટર પસંદ કરો.",
  AppStrings.selectDoctor: "ડૉક્ટર પસંદ કરો",
  AppStrings.searchDoctor: "ડૉક્ટર શોધો",
  AppStrings.newVersionAvailable: 'નવું સંસ્કરણ ઉપલબ્ધ છે. કૃપા કરીને તેમાં અપગ્રેડ કરો.',
  AppStrings.update: 'અપડેટ કરો',
};
