import 'package:rosewell_life_science/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.phoneNumber: "फ़ोन नंबर",
  AppStrings.enterPhoneNumber: "फोन नंबर दर्ज करें",
  AppStrings.pleaseEnterPhoneNumber: "कृपया फ़ोन नंबर दर्ज करें।",
  AppStrings.pleaseEnterValidPhoneNumber: "कृपया एक वैध नंबर डालें।",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पास वर्ड दर्ज करें",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें।",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.fileIsSavedToDownloadFolder: "फ़ाइल को फ़ोल्डर डाउनलोड करने के लिए सहेजा गया है।",
  AppStrings.next: "अगला",
  AppStrings.areYouSureYouWantToExitTheApp: "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  AppStrings.no: "नहीं",
  AppStrings.yesExit: "हाँ, बाहर निकलें",
  AppStrings.hello: "नमस्ते ",
  AppStrings.presentationForDoctors: "डॉक्टरों के लिए प्रस्तुति",
  AppStrings.presentation: "प्रस्तुति",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.medicineDetails: "औषधि विवरण",
  AppStrings.addMedicineDetails: "औषधि विवरण जोड़ें",
  AppStrings.editMedicineDetails: "औषधि विवरण संपादित करें",
  AppStrings.addMedicine: "दवा जोड़ें",
  AppStrings.editMedicine: "चिकित्सा संपादित करें",
};
