import 'package:rosewell_life_science/Constants/app_strings.dart';

Map<String, String> hiIN = <String, String>{
  AppStrings.login: "लॉग इन करें",
  AppStrings.phoneNumber: "फ़ोन नंबर",
  AppStrings.enterPhoneNumber: "फोन नंबर दर्ज करें",
  AppStrings.pleaseEnterPhoneNumber: "कृपया फ़ोन नंबर दर्ज करें।",
  AppStrings.pleaseEnterValidPhoneNumber: "कृपया एक वैध नंबर डालें।",
  AppStrings.password: "पासवर्ड",
  AppStrings.enterPassword: "पास वर्ड दर्ज करें",
  AppStrings.pleaseEnterPassword: "कृपया पासवर्ड दर्ज करें।",
  AppStrings.temporaryServiceIsNotAvailable: "अस्थायी सेवा उपलब्ध नहीं है।",
  AppStrings.fileIsSavedToDownloadFolder: "फ़ाइल को फ़ोल्डर डाउनलोड करने के लिए सहेजा गया है।",
  AppStrings.next: "अगला",
  AppStrings.hello: "नमस्ते 🙏,",
  AppStrings.createOrder: "ऑर्डर बनाएँ",
  AppStrings.settings: "सेटिंग्स",
  AppStrings.changeLanguage: "भाषा बदलें",
  AppStrings.english: "English",
  AppStrings.gujarati: "ગુજરાતી",
  AppStrings.hindi: "हिंदी",
  AppStrings.addStock: "स्टॉक जोड़ें",
  AppStrings.availableStock: "मौजूदा भंडार",
  AppStrings.pendingOrders: "लंबित ऑर्डर",
  AppStrings.challan: "चालान",
  AppStrings.category: "वर्ग",
  AppStrings.selectCategory: "श्रेणी चुनना",
  AppStrings.noDataFound: "डाटा प्राप्त नहीं हुआ",
  AppStrings.handle: "हैंडल",
  AppStrings.mainDoor: "मैन डोर",
  AppStrings.dabbi: "डब्बी",
  AppStrings.pleaseSelectCategory: "कृपया श्रेणी का चयन करें।",
  AppStrings.add: "जोड़ना",
  AppStrings.product: "उत्पाद",
  AppStrings.selectProduct: "उत्पाद का चयन करें",
  AppStrings.pleaseSelectProduct: "कृपया उत्पाद चुनें।",
  AppStrings.enterProductName: "उत्पाद का नाम दर्ज करें",
  AppStrings.size: "साईज़",
  AppStrings.selectSize: "साईज़ का चयन करें",
  AppStrings.select: "चुनना",
  AppStrings.searchSize: "साईज़ खोजे",
  AppStrings.searchProduct: "उत्पाद खोजे",
  AppStrings.three: '३',
  AppStrings.four: '४',
  AppStrings.six: '६',
  AppStrings.eight: '८',
  AppStrings.ten: '१॰',
  AppStrings.twelve: '१२',
  AppStrings.enterProductSize: 'उत्पाद का साईज़ दर्ज करें',
  AppStrings.size3QuantityWeight: 'साईज़ ३ मात्रा और वजन',
  AppStrings.size4QuantityWeight: 'साईज़ ४ मात्रा और वजन',
  AppStrings.size6QuantityWeight: 'साईज़ ६ मात्रा और वजन',
  AppStrings.size8QuantityWeight: 'साईज़ ८ मात्रा और वजन',
  AppStrings.size10QuantityWeight: 'साईज़ १॰ मात्रा और वजन',
  AppStrings.size12QuantityWeight: 'साईज़ १२ मात्रा और वजन',
  AppStrings.enterQuantity: 'मात्रा दर्ज करें (नंग)',
  AppStrings.enterWeight: 'वजन दर्ज करें (किग्रा)',
  AppStrings.enterWeightOfSinglePiece: 'एक नंग का वजन दर्ज करें',
  AppStrings.pleaseEnterProductSize: 'कृपया उत्पाद का साईज़ दर्ज करें.',
  AppStrings.pleaseSelectProductSize: 'कृपया उत्पाद का साईज़ चुनें।',
  AppStrings.pleaseEnterQuantity: 'कृपया मात्रा दर्ज करें।',
  AppStrings.pleaseEnterWeight: 'कृपया वजन दर्ज करें।',
  AppStrings.reset: 'रीसेट',
  AppStrings.gram: 'ग्राम',
  AppStrings.kilogram: 'किलोग्राम (किग्रा)',
  AppStrings.pleaseSelectUnitOfWeight: 'कृपया वजन की इकाई का चयन करें।',
  AppStrings.selectUnitOfWeight: 'वजन की इकाई का चयन करें',
  AppStrings.firstEnterWeightOfSinglePieceAndUnitOfWeight: 'पहले एक टुकड़े और वजन की इकाई का वजन दर्ज करें।',
  AppStrings.quantityMustBeAFractionValue: 'मात्रा एक अंश मूल्य होना चाहिए।',
  AppStrings.logOut: 'लॉग आउट',
  AppStrings.loginSuccessfully: 'सफलतापूर्वक लॉगिन हुआ।',
  AppStrings.invalidPhoneOrPassword: 'अमान्य फोन या पासवर्ड',
  AppStrings.weightOfPiece: 'नंग का वजन: ',
  AppStrings.availableStockQuantityWeight: 'उपलब्ध स्टॉक (मात्रा/वजन [किग्रा]): ',
  AppStrings.pieces: ' नंग',
  AppStrings.orderOfSize3: 'साईज़ ३ का ऑर्डर',
  AppStrings.orderOfSize4: 'साईज़ ४ का ऑर्डर',
  AppStrings.orderOfSize6: 'साईज़ ६ का ऑर्डर',
  AppStrings.orderOfSize8: 'साईज़ ८ का ऑर्डर',
  AppStrings.orderOfSize10: 'साईज़ १॰ का ऑर्डर',
  AppStrings.orderOfSize12: 'साईज़ १२ का ऑर्डर',
  AppStrings.orderOfSizeCustom: 'साईज़ कस्टम का ऑर्डर',
  AppStrings.pleaseSelectAnySizeForTheOrder: 'कृपया ऑर्डर के लिए किसी भी साईज़ का चयन करें।',
  AppStrings.ordersHistory: 'ऑर्डर की सूची',
  AppStrings.addNewProduct: 'नया उत्पाद जोड़ें',
  AppStrings.pleaseEnterProductName: 'कृपया उत्पाद का नाम दर्ज करें।',
  AppStrings.totalQuantity: 'कुल मात्रा: ',
  AppStrings.totalWeight: 'कुल वजन: ',
  AppStrings.quantity: 'मात्रा: ',
  AppStrings.weight: 'वज़न: ',
  AppStrings.thisSizeOfProductNotRegistered: 'उत्पाद की यह साईज़ पंजीकृत नहीं है. सबसे पहले, \'स्टॉक जोड़ें\' के माध्यम से साईज़ जोड़ें।',
  AppStrings.done: 'हो गया',
  AppStrings.cancel: 'रद्द करना',
  AppStrings.orderDate: 'आर्डर की तारीख: ',
  AppStrings.orderTime: 'आर्डर की समय: ',
  AppStrings.quantityAndWeight: 'मात्रा और वजन',
  AppStrings.partyName: 'पार्टी का नाम',
  AppStrings.enterPartyName: 'पार्टी का नाम दर्ज करें',
  AppStrings.pleaseEnterPartyName: 'कृपया पार्टी का नाम दर्ज करें।',
  AppStrings.productName: 'प्रोडक्ट का नाम: ',
  AppStrings.stockNotAvailable: 'स्टॉक उपलब्ध नहीं है।',
};
